import {
  UtensilsCrossed, Car, Receipt, ShoppingBag, Film, HeartPulse, ShoppingCart,
  PiggyBank, Heart, MoreHorizontal, Plane, Home, GraduationCap, Smartphone,
  Camera, Mountain, Gift, Star, Trophy, Coffee, Dumbbell, Wifi, Zap, Book,
  Music, Gamepad2, Briefcase, Wrench, Bus, Globe, Shield, Users, Scissors,
  Fuel, MapPin, Building2, Package, Baby, Bike, Train, Target, Wallet,
  Laptop, Headphones, Watch, Pizza, Apple, Stethoscope, Phone, Utensils,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  UtensilsCrossed,
  Car,
  Receipt,
  ShoppingBag,
  Film,
  HeartPulse,
  ShoppingCart,
  PiggyBank,
  Heart,
  MoreHorizontal,
  Plane,
  Home,
  GraduationCap,
  Smartphone,
  Camera,
  Mountain,
  Gift,
  Star,
  Trophy,
  Coffee,
  Dumbbell,
  Wifi,
  Zap,
  Book,
  Music,
  Gamepad2,
  Briefcase,
  Wrench,
  Bus,
  Globe,
  Shield,
  Users,
  Scissors,
  Fuel,
  MapPin,
  Building2,
  Package,
  Baby,
  Bike,
  Train,
  Target,
  Wallet,
  Laptop,
  Headphones,
  Watch,
  Pizza,
  Apple,
  Stethoscope,
  Phone,
  Utensils,
}

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? MoreHorizontal
}

/** Icons available in the category/goal picker UI */
export const PICKER_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: 'UtensilsCrossed', icon: UtensilsCrossed },
  { name: 'Utensils', icon: Utensils },
  { name: 'Pizza', icon: Pizza },
  { name: 'Coffee', icon: Coffee },
  { name: 'Apple', icon: Apple },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'Car', icon: Car },
  { name: 'Bus', icon: Bus },
  { name: 'Bike', icon: Bike },
  { name: 'Train', icon: Train },
  { name: 'Plane', icon: Plane },
  { name: 'Fuel', icon: Fuel },
  { name: 'Receipt', icon: Receipt },
  { name: 'Wallet', icon: Wallet },
  { name: 'Film', icon: Film },
  { name: 'Music', icon: Music },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Headphones', icon: Headphones },
  { name: 'HeartPulse', icon: HeartPulse },
  { name: 'Stethoscope', icon: Stethoscope },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'Heart', icon: Heart },
  { name: 'Baby', icon: Baby },
  { name: 'Users', icon: Users },
  { name: 'Home', icon: Home },
  { name: 'Building2', icon: Building2 },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Laptop', icon: Laptop },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Phone', icon: Phone },
  { name: 'Wifi', icon: Wifi },
  { name: 'Zap', icon: Zap },
  { name: 'Globe', icon: Globe },
  { name: 'Gift', icon: Gift },
  { name: 'Package', icon: Package },
  { name: 'Book', icon: Book },
  { name: 'Camera', icon: Camera },
  { name: 'Watch', icon: Watch },
  { name: 'Scissors', icon: Scissors },
  { name: 'Wrench', icon: Wrench },
  { name: 'Mountain', icon: Mountain },
  { name: 'MapPin', icon: MapPin },
  { name: 'Shield', icon: Shield },
  { name: 'Star', icon: Star },
  { name: 'Trophy', icon: Trophy },
  { name: 'Target', icon: Target },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'MoreHorizontal', icon: MoreHorizontal },
]

export const GOAL_ICONS = [
  'PiggyBank', 'Plane', 'Home', 'Car', 'GraduationCap',
  'Heart', 'Smartphone', 'Camera', 'Mountain', 'Gift', 'Star', 'Trophy',
] as const

export const PRESET_COLORS = [
  '#f97316', '#ef4444', '#ec4899', '#a855f7',
  '#3b82f6', '#06b6d4', '#14b8a6', '#22c55e',
  '#10b981', '#eab308', '#f43f5e', '#6b7280',
]
